!function(window){'use strict';var document=window.document,location=window.location;function getHost(url){var a=document.createElement('a'),host;a.href=url;host=a.host;a=null;return host;}
function isHostOrSubhost(host,targetHost){return host===targetHost||host.indexOf('.'+targetHost)>0;}
function getCookie(name){name='; '+encodeURIComponent(name)+'=';var cookie='; '+document.cookie,beginPos=cookie.indexOf(name),endPos;if(beginPos===-1){return null;}
beginPos+=name.length;endPos=cookie.indexOf(';',beginPos);if(endPos===-1){endPos=cookie.length;}
return decodeURIComponent(cookie.substring(beginPos,endPos));}
function setCookie(name,value,expires){var cookie=encodeURIComponent(name)+'='+encodeURIComponent(value)+'; path=/; domain=56.com';if(expires){cookie+='; expires='+(new Date((new Date()).getTime()+expires*60*1000)).toUTCString();}
document.cookie=cookie;}
function parseQueryString(str){if(str){str=str.replace(/^[#?]/,'');}
var data={};if(str){str=str.replace(/(?:^|&)([^&]+)=([^&]+)/g,function($0,$1,$2){var value=$2;try{value=decodeURIComponent(value);}catch(e){}
data[$1]=value;return'';});}
return data;}
var isMobile=(function(){var ua=window.navigator.userAgent,mobileRules=[/\bWindows\sPhone\b/,/\bWindows\s?Mobile\b/,/\bWindows\sCE\b/,/\b(?:iPad|iPod|iPhone|iOS)\b/,/\bOS(?:\s(?:[\d_.]+))?\slike\sMac\sOS\sX\b/,/\bAndroid;?\b/,/\bAdr\s(?:[\d.]+)(?:\b|_)/,/\bYunOs\b/,/\b(?:Symbian|SymbOS)/,/\b(?:BlackBerry|BB10)\b/],result;for(var i=0;i<mobileRules.length;i++){result=mobileRules[i].test(ua);if(result){break;}}
return result||(ua.indexOf('Linux')!==-1&&!/\bLinux;?\s(?:x86|i[356]86)\b/.test(ua));})();function getFlashVersion(){var result='-1';if(isMobile){return result;}
var swf,navigator=window.navigator;if(window.ActiveXObject){try{swf=new window.ActiveXObject('ShockwaveFlash.ShockwaveFlash');}catch(e){}
if(swf){try{result=swf.GetVariable('$version').split(' ')[1].replace(/\,/g,'.');}catch(e){}}}else if(navigator.plugins&&navigator.plugins.length>0){swf=navigator.plugins['Shockwave Flash'];if(swf){result=swf.description.replace(/^Shockwave\s+Flash\s+/i,'').replace(/[^\d]+/g,'.');}else{var ua=navigator.userAgent.toLowerCase();if(ua.indexOf('webtv/2.6')!=-1){result=4;}else if(ua.indexOf('webtv/2.5')!=-1){result=3;}else if(ua.indexOf('webtv')!=-1){result=2;}}}
result=result.split('.');if(result.length>2){result.length=2;}
return result.join('.');}
var imgs={};function getImg(url,data){var querystring=[];if(data){for(var i in data){querystring.push(encodeURIComponent(i)+'='+(data[i]==null?'':encodeURIComponent(data[i])));}}
if(querystring.length){url+=(url.indexOf('?')===-1?'?':'&')+querystring.join('&');}
var img=new Image(),imgId=Math.random();imgs[imgId]=img;img.onload=img.onerror=img.onabort=function(){delete imgs[imgId];};img.src=url;}
var _page_=window._page_,referrer=document.referrer,referrerHost=referrer?getHost(referrer):'',unionInfo=(getCookie('u_info')||'').split('--');if(!referrer){try{if(window.opener){referrer=window.opener.location.href;}}catch(e){}}
var statData={statid:window.webid||'undefined',isunion:getCookie('u_cid')?1:0,unionid:unionInfo[0]||'',siteid:unionInfo[1]||'',channelid:'',prod:_page_?(_page_.prod||''):'',cid:_page_?(_page_.cid||''):'',r:referrer,l:location.href,res:window.screen.width+'x'+window.screen.height,flashver:getFlashVersion(),bid:'',broadcast_channel:getCookie('broadcast_channel')||'',platform:'pc'};if(!statData.broadcast_channel&&referrerHost&&!isHostOrSubhost(referrerHost,'56.com')){setCookie('broadcast_channel',referrerHost);statData.broadcast_channel=referrerHost;}
var memberId=getCookie('member_id');if(memberId){var temp=memberId.indexOf('@'),userId=temp===-1?memberId:memberId.substring(0,temp);if(userId&&userId.indexOf('guest')===-1&&userId!=='deleted'){statData.bid=memberId;}}
if(_page_&&_page_.vcid!=null){statData.acid=_page_.vcid;}
if('channel'==statData.statid){statData.channelid=location.host.split('.')[0];}
if(!statData.isunion&&referrerHost){var unions=[{host:'baidu.com',unionid:'baidu',siteid:1},{host:'.9991.',unionid:'9991',siteid:0},{host:'.2345.',unionid:'9991',siteid:0},{host:'hao123.com',unionid:'hao123',siteid:0},{host:'video.56.com',unionid:'video56',siteid:1},{host:'so.56.com',unionid:'so56',siteid:1},{host:'hao.qq.com',unionid:'haoqq',siteid:1}];for(var i=0,union;union=unions[i];i++){if(referrerHost.indexOf(union.host)!==-1){statData.isunion=1;statData.unionid=union.unionid;statData.siteid=union.siteid;setCookie('u_cid',statData.isunion);setCookie('u_info',union.unionid+'--'+union.siteid);break;}}}
var urlParams=parseQueryString(location.search||location.hash);if(urlParams.unid){statData.isunion=1;statData.unionid=urlParams.unid;statData.siteid=urlParams.usid;setCookie('u_cid',statData.isunion);setCookie('u_info',statData.unionid+'--'+statData.siteid);}
var externalStatData=window.__statData__;if(externalStatData){for(var i in externalStatData){if(statData[i]==null){statData[i]=externalStatData[i];}}}
if(statData.statid==='shipai'){getImg('http://stat2.stat.v-56.com/'+(isMobile?'stat_m.gif':'stat.gif'),statData);}else{getImg('http://stat2.stat.v-56.com/stat.gif',statData);if(isMobile){getImg('http://stat2.stat.v-56.com/stat_m.gif',statData);}}!function(){var channel={'123.sogou.com':'f706392d15c1fe51','kan.sogou.com':'a18ac9fe64557993','v.sogou.com':'571714e730997ec2','tv.sogou.com':'69346951307238ed','www.sogou.com':'abbdd136abdb8172','hao123.com':'a7f04e0e6d9886ea','www.baidu.com':'50e48c6168d7b908','video.baidu.com':'f9260ff3c94091e2','hao.360.cn':'3f4c4b3afde8634b','v.360.cn':'cea0490af0f0aa43','www.sohu.com':'7d182a02ec0c2a46','so.360.cn':'8a61ff9b47bb2e80'};var ch=urlParams.ch_key,pvid=urlParams.pvid;if(!ch&&pvid&&pvid.indexOf('tc_')==0){switch(pvid){case'tc_video':ch='b11e7053fc403c02';break;case'tc_ent':ch='0f07d828108240ca';break;case'tc_news_video':ch='254e14cc00931184';break;default:ch='b744e8343dba4c5c';break;}}
if(!ch&&referrer){for(var type in channel){if(referrer.indexOf(type)>-1){ch=channel[type];break;}}}
var aureole=urlParams.aureole;if(aureole){ch='aureole_'+aureole;}
if(ch){setCookie('ch_key',ch);}
var lqd=urlParams.lqd,lcode=urlParams.lcode,txid=urlParams.txid,lmcc=urlParams.lmcc;var oth_Exclude=['360kan.com','baidu.com','baidu.mobi','baidu.cn','hao123.com','360.cn','3600.com','c.360webcache.com','so.com','duba.net','duba.com','rising.cn','sogou.com','soso.com','2345.com','2345x.com','2345y.com'];for(var i=0;i<oth_Exclude.length;i++){if(lmcc==='1'||referrer.indexOf(oth_Exclude[i])!==-1){lqd='';lcode='';setCookie('_LQD','',-1);setCookie('_LCODE','',-1);break;}}
lqd&&setCookie('_LQD',lqd);lcode&&setCookie('_LCODE',lcode);txid&&setCookie('_TXID',txid);}();!function(){var fuidInCookie=getCookie('fuid');function setFUIDToCookie(fuid){setCookie('fuid',fuid,100*24*60);}
function createFUID(){var n=1000,ran_start=n,ran_end=n+Math.pow(10,7),r=Math.random();r=(r<0.1)?(r+0.1):r;r=Math.floor(ran_start+r*ran_end);var fuid=(+new Date).toString()+r.toString();setFUIDToCookie(fuid);return fuid;}
function once(fn){var returnValue;return function(){if(fn){returnValue=fn.apply(this,arguments);fn=null;}
return returnValue;};}
var sendRequest=once(function(fuid,otherParams){var videoInfo=window.videoInfo,sohuVideoInfo=window.sohuVideoInfo,videoData=window.videoData;var sohuStatData={statid:window.webid||'undefined',url:statData.l+(statData.l.indexOf('?')===-1?'?':'&')+'statid='+(window.webid||'undefined'),refer:statData.r,fuid:fuid||createFUID(),istoploc:window.top===window.self?'t':'f',passport:statData.bid,islogin:statData.bid?'t':'f',catecode:statData.cid,playlistid:'',vid:'',lf:getCookie('landingrefer')||'',ugu:'',ugcode:'',oth:getCookie('_LQD')||'',cd:getCookie('_LCODE')||''};if(sohuVideoInfo){sohuStatData.vid=sohuVideoInfo.vid;sohuStatData.playlistid=sohuVideoInfo.pid;sohuStatData.ugu=sohuVideoInfo.ugu;sohuStatData.ugcode=sohuVideoInfo.ugcode;}else if(videoInfo){sohuStatData.vid=videoInfo.id;sohuStatData.playlistid=videoInfo.aid;}else if(videoData){sohuStatData.vid=videoData.vid;sohuStatData.playlistid=videoData.aid;}
if(!sohuStatData.lf&&referrerHost&&!isHostOrSubhost('56.com')){sohuStatData.lf=document.referrer;setCookie('landingrefer',sohuStatData.lf);}
var url='http://pv.hd.sohu.com/pvpb.gif';if(otherParams){url+='?'+otherParams;}
getImg(url,sohuStatData);});if(statData.flashver==-1){sendRequest(fuidInCookie);}else{var flashId='uid_'+Math.random().toString(36).substr(2);window.gotPlayerUID=function(fuid_deprecated,otherParams){var swf=document.getElementById(flashId),fuid=fuidInCookie;if(!swf){return;}
if(!fuid){try{fuid=swf.getData('id');setFUIDToCookie(fuid);}catch(e){}
fuid=fuid||createFUID();}
try{swf.setData('id',fuid);}catch(e){}
sendRequest(fuid,otherParams);};var renderFlash=function(src,attrs,params){var html='<object'+' type="application/x-shockwave-flash"';for(var a in attrs){html+=' '+a+'="'+attrs[a]+'"';}
var ua=window.navigator.userAgent;if(ua.indexOf('MSIE')===-1&&ua.indexOf('Trident')===-1){html+=' data="'+src+'"';}
html+='>';html+='<param name="movie" value="'+src+'" />';for(var p in params){html+='<param name="'+p+'" value="'+params[p]+'" />';}
html+='</object>';return html;};var div=document.createElement('div');div.style.position='absolute';div.style.right=div.style.bottom=0;div.innerHTML=renderFlash('http://s2.56img.com/script/fn/stat/v4/player_getuid.swf',{id:flashId,name:flashId,width:1,height:1,style:'position: absolute; right: 0; bottom: 0;'},{allowScriptAccess:'always',wmode:'transparent'});document.body.insertBefore(div,document.body.firstChild);setTimeout(function(){sendRequest(fuidInCookie);},10000);}}();}(window);(function(G,D,s,c,p){c={UA:'UA-56-000001',NO_FLS:0,WITH_REF:0,URL:'http://s1.56img.com/script/fn/stat/v3/iwt-min.js?v=20120809.js'};G._iwt?G._iwt.track(c,p):(G._iwtTQ=G._iwtTQ||[]).push([c,p]),!G._iwtLoading&&lo();function lo(t){G._iwtLoading=1;s=D.createElement('script');s.src=c.URL;t=D.getElementsByTagName('script');t=t[t.length-1];t.parentNode.insertBefore(s,t);}})(this,document);